### ISSUE TITLE
Uncaught ReferenceError: __DEFINES__ is not defined

### ISSUE THREAD

**Issue by enigmazack** [antfu/vitesse-webext#19]
I just clone the template and run 'pnpm i' and 'pnpm dev', and load the extension to chrome, but I get this error
```
Uncaught ReferenceError: __DEFINES__ is not defined
```
for the backgound script. This error introduced from this file
https://github.com/vitejs/vite/blob/fa30f76e49de0ca8abd96c1fd866da0512ed29b9/packages/vite/src/client/env.ts
I try to use yarn and firefox, same error.

**Comment by wensonsmith** [comment]
back to vite 2.4.3 works

**Comment by enigmazack** [comment]
> 2.4.3

Worked, a lot thanks

**Comment by eladcandroid** [comment]
I'm still facing it, even with Vite 2.5.1

**Comment by tmkx** [comment]
It's because that the background script imports `/@vite/client` since [this PR](https://github.com/antfu/vitesse-webext/pull/16/files#diff-02f835f2433cc097b2cdb594850494d62b1a98f969efc91cfb3cbf18b2d57d01R6), and then Vite will pre-bundle the deps, but, pre-bundling will not replace magic constants such as `__DEFINES__`.

You can try this workaround:
```diff
 optimizeDeps: {
   include: ['vue', '@vueuse/core'],
-   exclude: ['vue-demi'],
+   exclude: ['vue-demi', '@vite/client', '@vite/env'],
 },
```
and then delete Vite's cache dir `node_modules/.vite`

This will be solved in https://github.com/vitejs/vite/pull/4716

**Comment by iceshu** [comment]
I have the some issue  with vite v2.9.14
![image](https://user-images.githubusercontent.com/6309056/182017951-c567e867-c8e0-446b-a05a-bf1a5e962add.png)
the dev env is ok but the product build is not work.
![image](https://user-images.githubusercontent.com/6309056/182017995-2d5de5e9-d68f-47ac-bb15-fdb921bfdb60.png)

**Comment by zypy333** [comment]
I met the same problem in another project. I reinstall a different verion of  nodejs may cause the problem.I guess the cache does not match the nodejs I used
I solved the problem by deleting the node_modules and the package-lock.json and rebuild the progress.

**Comment by jessfeliciano** [comment]
Just wanted to contribute a bit here since I ran into the same issue and was able to finally figure it out. It turns out that it was because I had this in my index.html: `<script type="module" src="/@vite/client"></script>`

I had initially updated my vite config file with this solution from above:

` optimizeDeps: {
   include: ['vue', '@vueuse/core'],
-   exclude: ['vue-demi'],
+   exclude: ['vue-demi', '@vite/client', '@vite/env'],
 },`
 
But this didn't make a difference for me for whatever reason. I decided to instead simply delete the script tag and I was able to get it all to work. 
 
 The clue for me was this post: https://github.com/vitejs/vite/issues/12344#issuecomment-1464853123
 
 I realized that having `<script type="module" src="/@vite/client"></script> ` in index.html was somehow causing this script tag to be recognized: `<script type="module" src="./src/main.jsx"></script>`
 
 I don't fully understand why, but I hope this is helpful for anyone else.

**Comment by suraj-jd** [comment]
> Just wanted to contribute a bit here since I ran into the same issue and was able to finally figure it out. It turns out that it was because I had this in my index.html: `<script type="module" src="/@vite/client"></script>`
> 
> I had initially updated my vite config file with this solution from above:
> 
> ` optimizeDeps: { include: ['vue', '@vueuse/core'],
> 
> * exclude: ['vue-demi'],
> 
> * exclude: ['vue-demi', '@vite/client', '@vite/env'],
>   },`
> 
> But this didn't make a difference for me for whatever reason. I decided to instead simply delete the script tag and I was able to get it all to work.
> 
> The clue for me was this post: [vitejs/vite#12344 (comment)](https://github.com/vitejs/vite/issues/12344#issuecomment-1464853123)
> 
> I realized that having `<script type="module" src="/@vite/client"></script> ` in index.html was somehow causing this script tag to be recognized: `<script type="module" src="./src/main.jsx"></script>`
> 
> I don't fully understand why, but I hope this is helpful for anyone else.

I took 2 days to search me on Google and find you 
Thanks - You saved my time and website.

**Comment by andreyselin** [comment]
I had this because of importing @vite/client.
I needed it for auto refreshing on as separate domain while running dev server locally.
When trying to run it as built app it seems to be missing something related to dev-server environment and fails.
