### ISSUE TITLE
[issue] - type of 'browser' is any

### ISSUE THREAD

**Issue by hnbnh** [antfu/vitesse-webext#63]
Hi, there's a problem with `browser` variable, its type should not be `any`.

## Steps to Reproduce
1. Clone the project & install dependencies.
2. Run `pnpm dev`.
3. Content of `src/auto-imports.d.ts`:
```ts
declare global {
  const browser: typeof import('webextension-polyfill')['default']
  // ...
}
```
4. The type of every `browser` variable is `any`.

**Comment by jevakallio** [comment]
I just ran into the same problem. The `webextension-polyfill` package exports a `Browser` type, so you can do this:

```diff
-    const browser: typeof import('webextension-polyfill')['default']
+   const browser: import("webextension-polyfill").Browser;
```

I'm not sending a PR for this since I'm not sure if this is the correct fix -- unsure why this has broken in the first place, or whether it's never worked correctly in the first place.
